### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by MastaDan9** [AlexCalamaro/BDOMonsterBot#1]
Hi, ran into a problem. It gives out an error on inserting a picture into discord.

```
Traceback (most recent call last):
  File "C:\Users\Tuh\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Tuh\Downloads\BDOMonsterBot-master\BDOMonsterBot-master\monsterbotpublic.py", line 99, in on_message
    if 'url' in attachment:
TypeError: argument of type 'Attachment' is not iterable
```

**Comment by AlexCalamaro** [comment]
It's likely that the python Discord package has been updated several times in the years since I made this.  I believe [this ](https://discordpy.readthedocs.io/en/stable/api.html) is the API reference in question if you want to look into it yourself, but I'm not able to provide support on this code at this time.
